/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        dark: '#282A3A',
        muted: '#776B5D',
        accent: '#BBAB8C',
        "inverse-on-surface": "#32302d",
        "outline": "#979084",
        "primary-container": "#bbab8c",
        "on-primary-fixed-variant": "#51452d",
        "on-tertiary-container": "#3e3f51",
        "error-container": "#93000a",
        "surface-variant": "#363432",
        "on-tertiary-fixed-variant": "#444557",
        "surface-container": "#211f1d",
        "surface-container-high": "#2c2a27",
        "secondary": "#d3c4b3",
        "secondary-container": "#52473b",
        "on-secondary-fixed-variant": "#4f4539",
        "on-secondary": "#382f23",
        "inverse-surface": "#e7e1dd",
        "error": "#ffb4ab",
        "on-background": "#e7e1dd",
        "primary": "#d7c6a6",
        "on-primary-container": "#4a3f27",
        "surface": "#151311",
        "on-primary": "#392f18",
        "on-secondary-container": "#c5b6a6",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3b3936",
        "on-tertiary-fixed": "#191a2a",
        "on-secondary-fixed": "#221a10",
        "on-tertiary": "#2e2f40",
        "tertiary-container": "#ababc0",
        "background": "#151311",
        "surface-container-highest": "#363432",
        "tertiary": "#c7c6dc",
        "surface-container-lowest": "#0f0e0c",
        "secondary-fixed-dim": "#d3c4b3",
        "inverse-primary": "#6a5d43",
        "surface-tint": "#d6c5a4",
        "on-surface": "#e7e1dd",
        "on-surface-variant": "#cec5b9",
        "tertiary-fixed": "#e1e0f7",
        "primary-fixed": "#f2e1bf",
        "outline-variant": "#4b463d",
        "on-primary-fixed": "#231a06",
        "tertiary-fixed-dim": "#c5c5da",
        "surface-container-low": "#1d1b19",
        "primary-fixed-dim": "#d6c5a4",
        "on-error": "#690005",
        "surface-dim": "#151311",
        "secondary-fixed": "#f0e0cf"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "container-margin": "24px",
        "base": "8px",
        "xs": "4px",
        "xl": "32px",
        "sm": "12px",
        "lg": "24px",
        "md": "16px"
      },
      fontFamily: {
        "h1": ["Inter"],
        "label-sm": ["Inter"],
        "kpi-value": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "h2": ["Inter"],
        "display-md": ["Inter"],
        "data-tabular": ["Inter"]
      },
      fontSize: {
        "h1": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "kpi-value": ["32px", { "lineHeight": "1.0", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "h2": ["20px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-md": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "data-tabular": ["14px", { "lineHeight": "1.0", "fontWeight": "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
